try {
    let a = 42;
} catch (er) {
    let b = "fail";
}
